version: "3.6"

services:
  # This is the service name used when running ddev commands accepting the
  # --service flag.
  prestashop_804:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-prestashop_804
    image: prestashop/prestashop:8.0.4
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    depends_on:
      - db
    ports:
      - 80
    volumes:
      # Bind a volume for instance persisting
      - psdata_804:/var/www/html
      # Bind a local module to your instance
      - type: bind
        source: ../ # local path to the module
        target: /var/www/html/modules/${DDEV_SITENAME} # path to be mounted in the container
      #- ../:/var/www/html/modules/${DDEV_SITENAME}
      - .:/mnt/ddev_config
      # `ddev-global-cache` gets mounted so we have the CAROOT
      # This is required so that the CA is available for `mkcert` to install
      - ddev-global-cache:/mnt/ddev-global-cache
    environment:
      # PrestaShop:
      - DB_SERVER=${DB_SERVER}
      - DB_PREFIX=ps804_
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}_804
      - PS_INSTALL_DB=${PS_INSTALL_DB}
      - PS_ERASE_DB=${PS_ERASE_DB}
      - PS_INSTALL_AUTO=${PS_INSTALL_AUTO}
      - PS_DEMO_MODE=${PS_DEMO_MODE}
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_DOMAIN=${DDEV_HOSTNAME}:8083
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_ALL_LANGUAGES=${PS_ALL_LANGUAGES}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=${PS_FOLDER_INSTALL}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_ENABLE_SSL=${PS_ENABLE_SSL}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      # Ddev:
      - HTTP_EXPOSE=8082:80
      - HTTPS_EXPOSE=8083:80
      - VIRTUAL_HOST=$DDEV_HOSTNAME
volumes:
  psdata_804: